export const BAD_APPLE_TEXT = `Ever on and on I continue circling With nothing but my hate in a carousel of agony Till slowly I forget and my heart starts vanishing And suddenly I see that I can't break free, I'm Slipping through the cracks of a dark eternity With nothing but my pain and the paralyzing agony To tell me who I am, who I was Uncertainty enveloping my mind Till I can't break free, and

Maybe it's a dream; maybe nothing else is real But it wouldn't mean a thing if I told you how I feel So I'm tired of all the pain, of the misery inside And I wish that I could live feeling nothing but the night You can tell me what to say; you can tell me where to go But I doubt that I would care, and my heart would never know If I make another move there'll be no more turning back Because everything will change, and it all will fade to black

Will tomorrow ever come? Will I make it through the night? Will there ever be a place for the broken in the light? Am I hurting? Am I sad? Should I stay, or should I go? I've forgotten how to tell. Did I ever even know? Can I take another step? I've done everything I can All the people that I see I will never understand If I find a way to change, if I step into the light Then I'll never be the same, and it all will fade to white

Ever on and on I continue circling With nothing but my hate in a carousel of agony Till slowly I forget and my heart starts vanishing And suddenly I see that I can't break free, I'm Slipping through the cracks of a dark eternity With nothing but my pain and the paralyzing agony To tell me who I am, who I was Uncertainty enveloping my mind Till I can't break free, and

Maybe it's a dream; maybe nothing else is real But it wouldn't mean a thing if I told you how I feel So I'm tired of all the pain, of the misery inside And I wish that I could live feeling nothing but the night You can tell me what to say; you can tell me where to go But I doubt that I would care, and my heart would never know If I make another move there'll be no more turning back Because everything will change, and it all will fade to black

If I make another move, if I take another step Then it all would fall apart. There'd be nothing of me left If I'm crying in the wind, if I'm crying in the night Will there ever be a way? Will my heart return to white? Can you tell me who you are? Can you tell me where I am? I've forgotten how to see; I've forgotten if I can If I opened up my eyes there'd be no more going back 'Cause I'd throw it all away, and it all would fade to black`

export const KAGEROU_TEXT = `The Kagerou Project — カゲロウプロジェクト — Heat Haze Project. A Japanese mixed-media project created by Jin, Shizen no Teki-P. It initially began as a series of Vocaloid songs that became increasingly popular following the release of the third song, Kagerou Daze. Eventually, a light novel and manga series, both under the name of Kagerou Daze, were released. In 2014, an anime by Shaft was also released under the name Mekakucity Actors.

Shintarō Kisaragi has not left his house in over two years, spending all day on his computer and getting ruthlessly teased by Ene, an annoying computer virus. When Shintarō spills a drink on his computer keyboard, he has to buy a replacement in person. Unfortunately, terrorists arrive and Shintaro is taken hostage. However, he meets a group of young people, including his own sister, called the Mekakushi Dan — メカクシ団 — the Blindfold Gang — who stop the criminals using mysterious powers. They then force Shintarō to join their group. Little does he know, the Mekakushi Dan are in for a never-ending summer.

The Mekakushi Dan is a group of teenagers who each possess a unique eye power, collectively known as the Eye Abilities. These abilities were born from the Heat Haze, a mysterious otherworld that exists within the endless August 15th. Each member awakened their power through a traumatic experience connected to death and the Heat Haze. The snake-like entities from the Heat Haze granted these abilities in exchange for trapping the teenagers in an endless loop of tragedy and rebirth.

Marry Kozakura, a quarter-Medusa, holds the power to combine all the eye abilities — the ability to redo the world. Every time the group reaches a tragic end, Marry unconsciously resets time, sending everyone back to relive the events of August 14th and 15th. The Kagerou Daze — the shimmering heat haze of an endless summer day — is both a prison and a second chance. The snake inside the Heat Haze feeds on the suffering of each loop, growing stronger with every reset.

Ayano Tateyama, the original leader of the Mekakushi Dan, discovered the truth about the loops before anyone else. Her father, Kenjirou, had been possessed by the Wide-Open Eyes Snake, which sought to gather all the snakes and eye abilities into a single vessel to gain a physical body. Ayano sacrificed herself, entering the Heat Haze to prevent her eye ability from being collected. Her death set the current cycle of events into motion.

Ene, the digital girl living in Shintarō's computer, is actually Takane Enomoto — a classmate of his from two years ago. She was trapped in the cyber world by the experiments of Kenjirou. Konoha, the android-like boy with incredible strength, was once Haruka Kokonose, Takane's gentle classmate whose frail body gave out. Both were victims of the same conspiracy that aimed to complete the snake's plan.

Kido, Seto, and Kano — the three childhood friends raised in an orphanage by Ayano's family — each carry scars that mirror their powers. Kido can erase her presence, Seto can read the minds of others, and Kano can deceive anyone's eyes. Momo Kisaragi, Shintarō's sister, draws all eyes to her whether she wants them or not. Hibiya Amamiya, the youngest, is trapped in loops within loops, watching someone he cares about die over and over in the heat haze.

The story asks whether it is possible to break free from a cycle of suffering — whether the bonds between people are strong enough to overcome a force that feeds on despair. In the final loop, the members of the Mekakushi Dan must confront not only the snake but the nature of their own grief, guilt, and the choices that led them here. The heat haze shimmers. August 15th begins again. But this time, they remember.`
